### ISSUE TITLE
LDSC Per Snp Heritability

### ISSUE THREAD

**Issue by kulmsc** [carlaml/LDpred-funct#1]
In the documentation and the paper you suggest using LDSC to get per SNP heritability values.  However, I am only able to achieve total heritability of a trait that is caused by the SNPs, not many values, one for each SNP.  Could you point me to the exact LDSC documentation that produces these per-SNP heritabilities.  Also, should I be generating partitioned heritability based off of functional annotation?  Thank you.

**Comment by carlaml** [comment]
Hi! I updated the README file (Input files- Point 2) with detailed instructions on how to get the per-SNP heritability. Please let me know if that helps.
Best, Carla
