### ISSUE TITLE
Separate genotyping files used for LD-reference and validation(PRS)

### ISSUE THREAD

**Issue by restuadi311** [carlaml/LDpred-funct#3]
Hi,

When using flag --gf [PLINK FILES], the plink files will be used for both LD-reference panel and validation, right?

Do you have any options (or flags) that separate these two functions?
Let say, I want to use 1000 Genome European plink files as the LD-reference panel, but using UK-Biobank plink files as my validation.

(Sorry, maybe you've mentioned this flag somewhere in the github pages, but I cannot find it, please guide me)

Thank you very much,

Restu

**Comment by carlaml** [comment]
Hi Restu,
Currently the software only supports using the genotypes from the validation as the LD-reference panel. 

Thanks,
Carla

**Comment by restuadi311** [comment]
OK, alright then.

Thank you very much for your answer, Carla.
Any plan to extend LDpred-funct to that direction (can separate validation and LD-ref)?

Thanks, again!
Restu

**Comment by carlaml** [comment]
Dear Restu, Yes, I plan to add that feature but probably I will be able to get to it by the end of summer. Thanks,
Carla
